// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlgjFVdw0hJdYQh8Ca10ZaC6CvZRss_sQ',
    appId: '1:740778088710:web:a90be6b05161fe651e6687',
    messagingSenderId: '740778088710',
    projectId: 'untitled1-6d058',
    authDomain: 'untitled1-6d058.firebaseapp.com',
    storageBucket: 'untitled1-6d058.appspot.com',
    measurementId: 'G-RWH7YT46GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXN3BLpjjT_e1VsAb71vxx65EC5LBmKJ4',
    appId: '1:740778088710:android:4cc5971b022b7ee21e6687',
    messagingSenderId: '740778088710',
    projectId: 'untitled1-6d058',
    storageBucket: 'untitled1-6d058.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtLlpyjwq4PznUO5_m4IXS_OspiARmvl8',
    appId: '1:740778088710:ios:1d8ed662aec5ef241e6687',
    messagingSenderId: '740778088710',
    projectId: 'untitled1-6d058',
    storageBucket: 'untitled1-6d058.appspot.com',
    iosBundleId: 'com.example.finalExam1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtLlpyjwq4PznUO5_m4IXS_OspiARmvl8',
    appId: '1:740778088710:ios:1d8ed662aec5ef241e6687',
    messagingSenderId: '740778088710',
    projectId: 'untitled1-6d058',
    storageBucket: 'untitled1-6d058.appspot.com',
    iosBundleId: 'com.example.finalExam1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlgjFVdw0hJdYQh8Ca10ZaC6CvZRss_sQ',
    appId: '1:740778088710:web:c574d7659b8cdb881e6687',
    messagingSenderId: '740778088710',
    projectId: 'untitled1-6d058',
    authDomain: 'untitled1-6d058.firebaseapp.com',
    storageBucket: 'untitled1-6d058.appspot.com',
    measurementId: 'G-Z2PEZTZPGM',
  );
}
